// *** This is a generated file; if you want to change it, please change the generator or the appropriate interface file
// 
// This file was generated by NetworkProxyBuilder, by Hugh Perkins hughperkins at gmail http://hughperkins.com
// 

using System;
using System.Net;

namespace OSMP.NetworkInterfaces
{
public class LockRpcToServer_ClientProxy : OSMP.NetworkInterfaces.ILockRpcToServer
{
   RpcController rpc;
   IPEndPoint connection;

   public LockRpcToServer_ClientProxy( RpcController rpc, IPEndPoint connection )
   {
      this.rpc = rpc;
      this.connection = connection;
   }
   public void RequestLock( System.Net.IPEndPoint netconnection, OSMP.NetworkInterfaces.IReplicated targetobject )
   {
      rpc.SendRpc( connection, "OSMP.NetworkInterfaces.ILockRpcToServer", "RequestLock",  new object[]{ netconnection, targetobject } );
   }
   public void RenewLock( System.Net.IPEndPoint netconnection, OSMP.NetworkInterfaces.IReplicated targetobject )
   {
      rpc.SendRpc( connection, "OSMP.NetworkInterfaces.ILockRpcToServer", "RenewLock",  new object[]{ netconnection, targetobject } );
   }
   public void ReleaseLock( System.Net.IPEndPoint netconnection, OSMP.NetworkInterfaces.IReplicated targetobject )
   {
      rpc.SendRpc( connection, "OSMP.NetworkInterfaces.ILockRpcToServer", "ReleaseLock",  new object[]{ netconnection, targetobject } );
   }
}
}
